services:
  - type: static
    name: on-the-record-web
    rootDir: web
    buildCommand: npm install && npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: EV_ACCOUNTS_URL
        sync: false
