-- Close out the TN Gov R primary pipeline row after live selection.
-- Re-audit returned 0 findings and rankable_topics = 5, so 'audited' is now accurate.
-- status_reason is cleared: it described work ("needs re-audit + live selection") that is done.
-- NOTE: 'audited' removes the race from the pipeline work queue, which is correct HERE only
-- because rankable_topics = 5. Never leave a race at 'audited' with rankable_topics = 0.

UPDATE essentials.readrank_race_pipeline SET
  status = 'audited',
  status_reason = NULL,
  notes = notes || E'\n---\nLIVE SELECTION 2026-08-02. Re-audit after the source-verification fixes: 0 findings (was 8). 10 of the 11 drafts are now live, one per (candidate, topic); all 5 topics are rankable two-way. quoted_candidates=3, rankable_topics=5 (counters refreshed).\nLIVE: deportation Blackburn 32980122 + Fritts eeff0ba4 | housing Blackburn afe1041e + Rose 5da17c8d | public-safety-approach Fritts 29d84e19 + Rose 8e8928c8 | school-vouchers Blackburn 9a65e83d + Fritts aeec06b1 | taxes Blackburn 577f9663 + Rose f53f338a.\nHELD BACK: Rose/school-vouchers d29d9032 -- readrank_selected stays false by curator decision; its editor_note opens "NOT FOR LIVE SELECTION".\n\nTOOLING PROBLEM, UNRESOLVED: the curator selected all 10 in /admin/readrank-quotes and NONE of the writes reached this database -- all 11 rows were still readrank_selected=false afterwards, with no duplicate politician rows and our quote_texts present under no other politician_id. Selection was applied by direct SQL instead, replicating selectReadrankQuote''s transaction (clear the politician+lower(topic_key) group, then set one row true). Root cause not established: the deployed ev-accounts DATABASE_URL is set in the Render dashboard, not in render.yaml, so the admin may be pointed at a different database, or the select calls failed without surfacing an error in the UI. Worth resolving before the next race is selected this way -- note that selectReadrankQuote does not touch updated_at, so timestamps cannot be used to tell a failed write from a successful one.\n\nStill open, non-blocking: Rose has no rankable school-vouchers position, and Fritts has none on taxes despite it being his signature issue (WKRN published only a paraphrase of his grocery-tax answer). Both would likely be fixed by ingesting the NewsChannel5 "Inside Politics" episode and the WKRN affordability interview -- see ingest-candidates.json in the staged directory.\nFull report: on-the-record docs/audits/2026-08-02-quote-audit-tn-gov-r.md.'
WHERE id = '2ba201ed-330a-4014-bb5c-b3a2792e26d0';
